substitutions:
  _APPLY_CHANGES: 'false'
  _ENV: 'undefined'
steps:
- id: 'context'
name: 'alpine'
entrypoint: 'sh'
args:
- '-c'
- |
    echo "***********************"
    echo "project           : $PROJECT_ID"
    echo "branch            : $BRANCH_NAME"
    echo "default_region    : ${_DEFAULT_REGION}"
    echo "***********************"

- id: 'project Init'
name: gcr.io/cloud-builders/gcloud
entrypoint: sh
args:
    - '-c'
    - |
      echo "***********************"
      echo "project   : $PROJECT_ID"
      echo "***********************"
      cd iac/init
      chmod +x init.sh
      ./init.sh ${PROJECT_ID}

# [START tf-init]
- id: 'Tterraform init'
name: 'hashicorp/terraform:1.2.1'
entrypoint: 'sh'
args:
- '-c'
- |
  cat iac/backend.tfvars 
  terraform init -input=false -no-color -upgrade -backend-config=iac/backend.tfvars 
# [END tf-init]
timeout: 5400s